services:
  postgres:
    image: postgres:17.5-bullseye
    # container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: base_01
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ciudades512
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django1:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: django_app_1
    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime:ro

    # Se quito la sección "ports" por no es necesario exponerlo al host cuando NGINX lo consume dentro de la red interna de docker
    mem_limit: 1g
    environment:
      - DEBUG=False
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      - DB_NAME=base_01
      - DB_USER=postgres
      - DB_PASSWORD=ciudades512
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    command: >
      /bin/bash -c "
      sleep 5 &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn proyecto_01.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  django2:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: django_app_2
    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime:ro
    mem_limit: 1g
    environment:
      - DEBUG=False
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      - DB_NAME=base_01
      - DB_USER=postgres
      - DB_PASSWORD=ciudades512
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

    # Aca se saco el migrate para que no haga el migrations de vuelta, ya lo hizo el Django1
    command: >
      /bin/bash -c "
      sleep 5 &&
      gunicorn proyecto_01.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  nginx:
    image: nginx:latest
    # container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./ssl/selfsigned.crt:/etc/ssl/certs/selfsigned.crt:ro
      - ./ssl/selfsigned.key:/etc/ssl/private/selfsigned.key:ro
    depends_on:
      - django1
      - django2
    command: nginx -g 'daemon off;'

volumes:
  postgres_data: