# Generated by Django 5.2.1 on 2025-05-24 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LugarTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Lugar de Trabajo',
                'verbose_name_plural': 'Lugares de Trabajo',
                'db_table': 'lugares_trabajo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('habil', 'Hábil'), ('inhabil', 'Inhábil'), ('feriado', 'Feriado'), ('no_laborable', 'No Laborable')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción (opcional)')),
                ('computa_vacaciones', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1, verbose_name='¿Computa Vacaciones?')),
            ],
            options={
                'verbose_name': 'Tipo de Día',
                'verbose_name_plural': 'Tipos de Días',
                'db_table': 'tipos_dias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=40, verbose_name='Legajo')),
                ('nombre', models.CharField(max_length=254, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=254, verbose_name='Apellidos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='Sexos')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='estructura.categoria', verbose_name='Categoría')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('lugar_trabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='estructura.lugartrabajo', verbose_name='Lugar de Trabajo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_invertida', models.CharField(max_length=8, verbose_name='Fecha YYYYMMDD')),
                ('tipo_dia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estructura.tipodia', verbose_name='Tipo de Día')),
            ],
            options={
                'verbose_name': 'Día',
                'verbose_name_plural': 'Días',
                'db_table': 'dias',
                'ordering': ['fecha_invertida'],
            },
        ),
    ]
