# Generated by Django 5.2.1 on 2025-08-04 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=1000)),
                ('honorarios', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ayudante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('anestesia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('servicio', models.CharField(max_length=50)),
                ('practica', models.CharField(blank=True, max_length=150)),
                ('activo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2)),
            ],
            options={
                'verbose_name': 'Prestación',
                'verbose_name_plural': 'Prestaciones',
                'db_table': 'prestaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('habil', 'Hábil'), ('inhabil', 'Inhábil'), ('feriado', 'Feriado'), ('no_laborable', 'No Laborable')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción (opcional)')),
                ('computa_vacaciones', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1, verbose_name='¿Computa Vacaciones?')),
            ],
            options={
                'verbose_name': 'Tipo de Día',
                'verbose_name_plural': 'Tipos de Días',
                'db_table': 'tipos_dias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('SAMIC', 'SAMIC'), ('Formenti', 'Formenti'), ('Residente', 'Residente')], max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Empleado',
                'verbose_name_plural': 'Tipos de Empleados',
                'db_table': 'tipos_empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.PositiveIntegerField(verbose_name='Legajo')),
                ('nombre', models.CharField(max_length=254, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=254, verbose_name='Apellidos')),
                ('dni', models.PositiveIntegerField(verbose_name='DNI')),
                ('cuil', models.CharField(max_length=13, verbose_name='CUIL')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2)),
                ('autorizante1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empleado_autorizante1', to=settings.AUTH_USER_MODEL, verbose_name='Autorizante 1')),
                ('autorizante2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empleado_autorizante2', to=settings.AUTH_USER_MODEL, verbose_name='Autorizante 2')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empleado_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tipo_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='estructura.tipoempleado', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activo', models.CharField(choices=[('s', 'Sí'), ('n', 'No')], default='s', max_length=1)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuestos',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, default='', max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.CharField(choices=[('s', 'Sí'), ('n', 'No')], default='s', max_length=1)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos_items_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos_items_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.presupuesto')),
            ],
            options={
                'verbose_name': 'Presupuesto Item',
                'verbose_name_plural': 'Presupuestos Items',
                'db_table': 'presupuestos_items',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoPrestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.presupuestoitem')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.prestacion')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones', to='estructura.presupuesto')),
            ],
            options={
                'verbose_name': 'Presupuesto Prestación',
                'verbose_name_plural': 'Presupuestos Prestaciones',
                'db_table': 'presupuestos_prestaciones',
            },
        ),
        migrations.CreateModel(
            name='SolicitudHorasSamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha solicitud')),
                ('fecha_hora_desde', models.DateTimeField(verbose_name='Fecha-Hora desde')),
                ('fecha_hora_hasta', models.DateField(verbose_name='Fecha-Hora hasta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado'), ('realizado', 'Realizado'), ('anulado', 'Anulado')], max_length=20)),
                ('autorizante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudhorassamic_autorizante', to=settings.AUTH_USER_MODEL, verbose_name='Autorizante')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estructura.empleado', verbose_name='Empleado')),
                ('finalizo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudhorassamic_finalizo', to=settings.AUTH_USER_MODEL, verbose_name='Finalizó')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudhorassamic_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Horas Samic',
                'verbose_name_plural': 'Solicitudes de Horas Samic',
                'db_table': 'solicitudes_horas_samic',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_invertida', models.CharField(max_length=8, verbose_name='Fecha YYYYMMDD')),
                ('tipo_dia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estructura.tipodia', verbose_name='Tipo de Día')),
            ],
            options={
                'verbose_name': 'Día',
                'verbose_name_plural': 'Días',
                'db_table': 'dias',
                'ordering': ['fecha_invertida'],
            },
        ),
    ]
