# Generated by Django 5.2.1 on 2025-08-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudhorassamic',
            name='minutos_solicitados',
            field=models.IntegerField(default=0, verbose_name='Minutos solicitados'),
        ),
    ]
