# Generated by Django 5.2.1 on 2025-08-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudhorassamic',
            name='fecha_hora_hasta',
            field=models.DateTimeField(verbose_name='Fecha-Hora hasta'),
        ),
    ]
