# Generated by Django 5.2.1 on 2025-06-10 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=150)),
                ('honorarios', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ayudante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('anestesia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('servicio', models.CharField(max_length=50)),
                ('practica', models.CharField(max_length=150)),
                ('activo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2)),
            ],
            options={
                'verbose_name': 'Prestación',
                'verbose_name_plural': 'Prestaciones',
                'db_table': 'prestaciones',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuestos',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.presupuesto')),
            ],
            options={
                'verbose_name': 'Presupuesto Item',
                'verbose_name_plural': 'Presupuestos Items',
                'db_table': 'presupuestos_items',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoPrestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.presupuestoitem')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.prestacion')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones', to='estructura.presupuesto')),
            ],
            options={
                'verbose_name': 'Presupuesto Prestación',
                'verbose_name_plural': 'Presupuestos Prestaciones',
                'db_table': 'presupuestos_prestaciones',
            },
        ),
    ]
