# Generated by Django 5.2.1 on 2025-06-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0002_prestacion_presupuesto_presupuestoitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='lugar_trabajo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='sexo',
        ),
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cuil',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='CUIL'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='legajo',
            field=models.PositiveIntegerField(verbose_name='Legajo'),
        ),
        migrations.DeleteModel(
            name='LugarTrabajo',
        ),
    ]
