# Generated by Django 5.2.1 on 2025-08-06 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0002_solicitudhorassamic_minutos_solicitados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudhorassamic',
            name='finalizo',
        ),
        migrations.AddField(
            model_name='solicitudhorassamic',
            name='anulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudhorassamic_anulo', to=settings.AUTH_USER_MODEL, verbose_name='Anuló'),
        ),
        migrations.AlterField(
            model_name='solicitudhorassamic',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], max_length=20),
        ),
    ]
