# Generated by Django 5.2.1 on 2025-08-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0003_remove_solicitudhorassamic_finalizo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estructura.tipoempleado', verbose_name='Tipo'),
        ),
    ]
