# Generated by Django 5.2.1 on 2025-06-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0003_remove_empleado_lugar_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cuil',
            field=models.CharField(default=0, max_length=13, verbose_name='CUIL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.PositiveIntegerField(default=11111111, verbose_name='DNI'),
            preserve_default=False,
        ),
    ]
