# Generated by Django 5.2.1 on 2025-06-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0004_alter_empleado_cuil_alter_empleado_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='categoria',
        ),
    ]
