# Generated by Django 5.2.1 on 2025-08-07 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0004_alter_empleado_tipo_empleado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='autorizante3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empleado_autorizante3', to=settings.AUTH_USER_MODEL, verbose_name='Autorizante 3'),
        ),
    ]
