# Generated by Django 5.2.1 on 2025-08-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0005_empleado_autorizante3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodia',
            name='nombre',
            field=models.CharField(choices=[('hábil', 'Hábil'), ('inhábil', 'Inhábil'), ('feriado', 'Feriado'), ('no_laborable', 'No Laborable')], max_length=20),
        ),
    ]
