# Generated by Django 5.2.1 on 2025-06-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0006_alter_empleado_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoitem',
            name='detalle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
