# Generated by Django 5.2.1 on 2025-06-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_presupuestoitem_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoitem',
            name='detalle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
