# Generated by Django 5.2.1 on 2025-07-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0009_tipoempleado_delete_categoria_empleado_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoitem',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
