# Generated by Django 5.2.1 on 2025-07-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0010_presupuestoitem_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestoitem',
            name='precio',
        ),
    ]
