# Generated by Django 5.2.1 on 2025-07-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0011_remove_presupuestoitem_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoitem',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
