# Generated by Django 5.2.1 on 2025-07-14 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0013_presupuesto_usuario_alter_prestacion_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='usuario',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
