# Generated by Django 5.2.1 on 2025-07-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0014_remove_presupuesto_usuario_presupuesto_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='activo',
            field=models.CharField(choices=[('s', 'Sí'), ('n', 'No')], default='s', max_length=1),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='activo',
            field=models.CharField(choices=[('s', 'Sí'), ('n', 'No')], default='s', max_length=1),
        ),
    ]
