# Generated by Django 5.2.1 on 2025-07-15 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0015_presupuesto_activo_presupuestoitem_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='eliminado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='eliminado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos_items_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='presupuestoitem',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos_items_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
