# Generated by Django 5.2.1 on 2025-08-03 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0016_presupuesto_eliminado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha solicitud')),
                ('fecha_desde', models.DateField(verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha hasta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado_sector', 'Autorizado Sector'), ('autorizado_rrhh', 'Autorizado RRHH')], max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estructura.empleado', verbose_name='Empleado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Vacaciones',
                'verbose_name_plural': 'Solicitudes de Vacaciones',
                'db_table': 'solicitud_vacaciones',
            },
        ),
    ]
